name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      uses: docker/login-action@v2.0.0
      with:
         username: azitmentor
         password: ${{ secrets.dockerpw }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag azitmentor/aticrmapp
        docker push azitmentor/aticrmapp
